"""add quantity field to products

Revision ID: 343d6e22ed70
Revises: a343990490b8
Create Date: 2025-10-27 13:25:01.004593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '343d6e22ed70'
down_revision: Union[str, Sequence[str], None] = 'a343990490b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=False))
    op.alter_column('orders', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
    op.drop_constraint(op.f('orders_ibfk_1'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('orders', 'total_price')
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('products', 'units',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('products', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('products', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.alter_column('products', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('products', 'units',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    op.add_column('orders', sa.Column('total_price', mysql.FLOAT(), nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_ibfk_1'), 'orders', 'users', ['user_id'], ['id'])
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('orders', 'total_amount')
    op.alter_column('order_items', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
