"""add new_table model

Revision ID: a343990490b8
Revises: 5ea3e23f0a32
Create Date: 2025-10-14 13:46:37.338570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a343990490b8'
down_revision: Union[str, Sequence[str], None] = '5ea3e23f0a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_column('products', 'quantity')

    # ### end Alembic commands ###
