"""Add created_at column to carts table

Revision ID: d82c30887bb5
Revises: 343d6e22ed70
Create Date: 2025-10-28 15:41:42.566273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd82c30887bb5'
down_revision: Union[str, Sequence[str], None] = '343d6e22ed70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('carts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('carts', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('carts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('carts', 'created_at')
    # ### end Alembic commands ###
